//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Faculty = new HashSet<Faculty>();
        }
    
        public int city_id { get; set; }
        public string city_name { get; set; }
        public int state_id { get; set; }
    
        public virtual State State { get; set; }
        public virtual ICollection<Faculty> Faculty { get; set; }
    }
}
