//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faculty
    {
        public Faculty()
        {
            this.FacultySubject = new HashSet<FacultySubject>();
            this.Student = new HashSet<Student>();
        }
    
        public int faculty_id { get; set; }
        public string code { get; set; }
        public string faculty_name { get; set; }
        public System.DateTime foundation_date { get; set; }
        public int university_id { get; set; }
        public int city_id { get; set; }
    
        public virtual City City { get; set; }
        public virtual University University { get; set; }
        public virtual ICollection<FacultySubject> FacultySubject { get; set; }
        public virtual ICollection<Student> Student { get; set; }
    }
}
