//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public State()
        {
            this.City = new HashSet<City>();
        }
    
        public int state_id { get; set; }
        public string state_name { get; set; }
        public int country_id { get; set; }
    
        public virtual ICollection<City> City { get; set; }
        public virtual Country Country { get; set; }
    }
}
