//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int student_id { get; set; }
        public string student_name { get; set; }
        public System.DateTime birth_date { get; set; }
        public int semester { get; set; }
        public int faculty_id { get; set; }
    
        public virtual Faculty Faculty { get; set; }
    }
}
